DROP TABLE if exists books;

CREATE TABLE books (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  author VARCHAR(40) NOT NULL,
  description MEDIUMTEXT NOT NULL
);

INSERT INTO books (title, author, description) 
VALUES ('Spectrum Women', 'Barb Cook', 'Barb Cook and 14 other autistic women describe life from a female autistic perspective, and present empowering, helpful and supportive insights from their personal experience for fellow autistic women. Dr. Michelle Garnett`s comments validate and expand the experiences described from a clinician`s perspective, and provide extensive recommendations.'),
('The Electricity of Every Living Thing', 'Katherine May', 'A life-affirming and perspective-shifting memoir of one woman`s walks in the walks as she comes to terms with her autism diagnosis. In August 2015, Katherine May set out to walk the 630-mile South West Coast Path. She wanted to understand why she had stopped coping with everyday life; why motherhood had been so overwhelming and isolating, and why the world felt full of inundation and expectations she can`t meet. Setting her feet down on the rugged and difficult path by the sea, the answer begins to unfold. It`s a chance encounter with a voice on the radio that sparks a realisation that she has Asperger`s Syndrome. The Electricity of Every Living Thing tells the story of the year in which Katherine comes to terms with her diagnosis. It leads to a re-evaluation of her life so far - a kinder one, which finally allows her to be different rather than simply awkward, arrogant or unfeeling. The physical and psychological journeys become inextricably entwined, and as Katherine finds her way across the untameable coast, she also finds the way to herself.mThis book is a life-affirming exploration of wild landscapes, what it means to be different and, above all, how we can all learn to make peace within our own unquiet minds.'),
('Don`t Mourn For Us', 'Jim Sinclair', 'Jim Sinclair`s 1993 essay “Don`t Mourn for Us” has influenced the neurodiversity movement since its publication. Sinclair`s essay stands out as particularly radical when considered within the context of other autistic writings from the 1980s and early 1990s. While writers such as Temple Grandin and Donna Williams introduced mainstream audiences to the concept of autistic people narrating their own experiences, their works still relied on ableist ideas about autism promoted by non-autistic scientific “experts” and parents. They positioned autism as a tragedy. Sinclair, who was very familiar with parent-centric autism culture, upended those notions by challenging the notion that parental grief was the inevitable result of autism. In doing so, Sinclair played a major role in establishing the intellectual and cultural foundations of neurodiversity.');